"""
Django settings for RecyclingBPM project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os  # <-- Umgebungsvariablen nutzen
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cz(6lu_=f_*yp&*k$c&so(+ls5eo3431d47(8dvbsl-8*5dehe'

# DEBUG über ENV steuerbar (lokal bleibt default True)
DEBUG = os.getenv("DJ_DEBUG", "true").lower() == "true"


# vertrauenswürdige Ursprünge für CSRF (Prod), sonst können 403 auftretten 
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv("DJ_CSRF_TRUSTED", "http://127.0.0.1:8000").split(",") if o.strip()]

# --- Hosts aus ENV (fällt zurück auf localhost)
ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJ_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'warenwirtschaft',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'RecyclingBPM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'warenwirtschaft' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'RecyclingBPM.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 20,
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'de-de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# --- Basis-Pfad (z.B. DJ_BASE_PATH=aba). Leer = Betrieb im Root.
BASE_PATH = os.getenv("DJ_BASE_PATH", "").strip("/")

# Static files
STATICFILES_DIRS = [BASE_DIR / "warenwirtschaft" / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# --- NEU: STATIC/MEDIA-URLs abhängig vom Unterpfad
if BASE_PATH:
    # Deutsch: App läuft unter /<BASE_PATH>, z. B. /aba
    FORCE_SCRIPT_NAME = f"/{BASE_PATH}"
    STATIC_URL = f"/{BASE_PATH}/static/"
    MEDIA_URL  = f"/{BASE_PATH}/media/"
else:
    # Deutsch: Lokaler Betrieb im Root
    FORCE_SCRIPT_NAME = None
    STATIC_URL = "/static/"
    MEDIA_URL  = "/media/"

MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'