from .barcode_generator_list_view import BarcodeGeneratorListView
from .barcode_generator_create_view import BarcodeGeneratorCreateView
from .barcode_generator_update_view import BarcodeGeneratorUpdateView
from .barcode_generator_detail_view import BarcodeGeneratorDetailView
from .barcode_generator_delete_view import BarcodeGeneratorDeleteView