from .material_list_view import MaterialListView
from .material_create_view import MaterialCreateView
from .material_update_view import MaterialUpdateView
from .material_delete_view import MaterialDeleteView