from .customer_list_view import CustomerListView
from .customer_update_view import CustomerUpdateView
from .customer_detail_view import CustomerDetailView
from .customer_create_view import CustomerCreateView
from .customer_delete_view import CustomerDeleteView