# Generated by Django 5.1.4 on 2025-08-30 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('delivery', models.BooleanField(default=False, verbose_name='material_delivery')),
                ('unload', models.BooleanField(default=False, verbose_name='material_unload')),
                ('recycling', models.BooleanField(default=False, verbose_name='material_recycling')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('avv_number', models.PositiveIntegerField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='warenwirtsc_name_d0edc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_receipt', models.CharField(blank=True, max_length=30, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_customer', to='warenwirtschaft.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_type', models.PositiveSmallIntegerField(choices=[(1, 'Container'), (2, 'Gitterbox'), (3, 'Palette'), (4, 'Ohne Behälter')])),
                ('material_other', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Aktiv'), (4, 'Erledigt')], default=1)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/delivery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units_for_delivery', to='warenwirtschaft.delivery')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_for_delivery_units', to='warenwirtschaft.material')),
            ],
        ),
        migrations.CreateModel(
            name='BarcodeGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('delivery_receipt', models.CharField(blank=True, max_length=100, null=True)),
                ('box_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Container'), (2, 'Gitterbox'), (3, 'Palette'), (4, 'Gelbe Waagen'), (5, 'Ohne Behälter')], null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Eingang'), (2, 'Vorsortierung'), (3, 'Abholung')], null=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/reusable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_for_barcode', to='warenwirtschaft.customer')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_for_barcode', to='warenwirtschaft.material')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.PositiveIntegerField(blank=True, null=True)),
                ('transport', models.PositiveSmallIntegerField(choices=[(1, 'Kunde'), (2, 'Eigen')])),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_for_customer', to='warenwirtschaft.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Unload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_type', models.PositiveSmallIntegerField(choices=[(1, 'Container'), (2, 'Gitterbox'), (3, 'Wagen'), (4, 'Ohne Behälter')])),
                ('material_other', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Aktiv'), (2, 'Bereit für Zerlegung'), (3, 'Bereit für Abholung'), (4, 'Erledigt')], default=1)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/unload/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('delivery_units', models.ManyToManyField(related_name='unload_for_delivery_unit', to='warenwirtschaft.deliveryunit')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_for_unload', to='warenwirtschaft.material')),
                ('shipping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unload_for_shipping', to='warenwirtschaft.shipping')),
            ],
        ),
        migrations.AddField(
            model_name='shipping',
            name='unload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unload_for_shipping', to='warenwirtschaft.unload'),
        ),
        migrations.CreateModel(
            name='Recycling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_type', models.PositiveSmallIntegerField(choices=[(1, 'Gitterbox'), (2, 'Palette'), (3, 'Gelbe Waagen'), (4, 'Ohne Behälter')])),
                ('material_other', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Aktiv'), (3, 'Bereit für Abholung'), (4, 'Erledigt')], default=1)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_for_recycling', to='warenwirtschaft.material')),
                ('shipping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recycling_for_shipping', to='warenwirtschaft.shipping')),
                ('unloads', models.ManyToManyField(related_name='recycling_for_unload', to='warenwirtschaft.unload')),
            ],
        ),
    ]
