# Generated by Django 5.1.4 on 2025-05-03 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_receipt', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Eingang'), (2, 'Zerlegung'), (3, 'Erledigt')], default=1)),
                ('delivery_type', models.PositiveSmallIntegerField(choices=[(1, 'Container'), (2, 'Gitterbox'), (3, 'Palette'), (4, 'Ohne Behälter')])),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveryunits', to='warenwirtschaft.delivery')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material', to='warenwirtschaft.material')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('avv_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='AVV-Nummer')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Straße')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stadt')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Anmerkung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='warenwirtsc_name_a9386b_idx'), models.Index(fields=['avv_number'], name='warenwirtsc_avv_num_19418f_idx')],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='warenwirtschaft.supplier'),
        ),
        migrations.CreateModel(
            name='Unload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unload_type', models.PositiveSmallIntegerField(choices=[(1, 'Gitterbox'), (2, 'Palette'), (3, 'Container'), (4, 'Ohne Behälter')])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purpose', models.PositiveSmallIntegerField(choices=[(1, 'Behandlung'), (2, 'Abholung'), (3, 'Entsorgung: Batterien'), (4, 'Entsorgung: Schadstoffe')])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Aktiv'), (2, 'Erledigt')], default=1)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('delivery_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unload_delivery_unit', to='warenwirtschaft.deliveryunit')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unload_material', to='warenwirtschaft.material')),
            ],
        ),
    ]
