# Generated by Django 5.1.4 on 2025-09-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcodegenerator',
            old_name='delivery_receipt',
            new_name='receipt',
        ),
        migrations.RemoveField(
            model_name='barcodegenerator',
            name='area',
        ),
        migrations.RemoveField(
            model_name='barcodegenerator',
            name='code',
        ),
        migrations.AddField(
            model_name='barcodegenerator',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='barcodegenerator',
            name='transport',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Kunde'), (2, 'Eigen')], default=1),
        ),
        migrations.AddField(
            model_name='recycling',
            name='barcode',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='barcode',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
