# Generated by Django 5.1.4 on 2025-05-07 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recycling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_type', models.PositiveSmallIntegerField(choices=[(1, 'Gitterbox'), (2, 'Palette'), (3, 'Gelbe Waagen'), (4, 'Ohne Behälter')])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target', models.PositiveSmallIntegerField(choices=[(1, 'Behandlung'), (2, 'Abholung'), (3, 'Entsorgung')])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Aktiv'), (2, 'Erledigt')], default=1)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recycling_material', to='warenwirtschaft.material')),
                ('unload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycling_unload', to='warenwirtschaft.unload')),
            ],
        ),
    ]
