# Generated by Django 5.1.4 on 2025-01-09 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryunits',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveryunits', to='warenwirtschaft.delivery'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='avv_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='AVV-Nummer'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bemerkung'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Straße'),
        ),
        migrations.CreateModel(
            name='Unloading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unload_type', models.PositiveSmallIntegerField(choices=[(1, 'Gitterbox'), (2, 'Palette'), (3, 'Ohne Behälter')])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purpose', models.PositiveSmallIntegerField(choices=[(1, 'Zerlegung'), (2, 'Reparatur'), (3, 'Entsorgung')])),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='warenwirtschaft.deliveryunits')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unload_device', to='warenwirtschaft.device')),
            ],
        ),
    ]
