# Generated by Django 5.1.4 on 2025-06-27 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reusablebarcode',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_for_barcode', to='warenwirtschaft.customer'),
        ),
        migrations.AlterField(
            model_name='reusablebarcode',
            name='target',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Eingang'), (1, 'Umladung'), (2, 'Aufbereitung'), (3, 'Abholung'), (4, 'Entsorgung'), (4, 'Zusatzdaten')], null=True),
        ),
    ]
