# Generated by Django 5.1.4 on 2025-06-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0002_reusablebarcode_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reusablebarcode',
            name='area',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Eingang'), (2, 'Umladung'), (3, 'Aufbereitung'), (4, 'Abholung'), (5, 'Entsorgung')], null=True),
        ),
        migrations.AlterField(
            model_name='reusablebarcode',
            name='box_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Container'), (2, 'Gitterbox'), (3, 'Palette'), (4, 'Gelbe Waagen'), (5, 'Ohne Behälter')], null=True),
        ),
        migrations.AlterField(
            model_name='reusablebarcode',
            name='target',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Eingang'), (2, 'Umladung'), (3, 'Aufbereitung'), (4, 'Abholung'), (5, 'Entsorgung'), (6, 'Zusatzdaten')], null=True),
        ),
    ]
