# Generated by Django 5.1.4 on 2025-05-10 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0002_recycling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.PositiveIntegerField(blank=True, null=True)),
                ('transport', models.PositiveSmallIntegerField(choices=[(1, 'K'), (2, 'E')])),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('box_type', models.PositiveSmallIntegerField(choices=[(1, 'Container'), (2, 'Gitterbox'), (3, 'Palette'), (4, 'Ohne Behälter')])),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='supplier',
            name='warenwirtsc_avv_num_19418f_idx',
        ),
        migrations.RenameField(
            model_name='deliveryunit',
            old_name='delivery_type',
            new_name='box_type',
        ),
        migrations.AddField(
            model_name='deliveryunit',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Umladung'), (2, 'Recycling'), (3, 'Abholung'), (4, 'Entsorgung')], default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_receipt',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_supplier', to='warenwirtschaft.supplier'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryunit',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units_for_delivery', to='warenwirtschaft.delivery'),
        ),
        migrations.AlterField(
            model_name='deliveryunit',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_for_delivery_units', to='warenwirtschaft.material'),
        ),
        migrations.AlterField(
            model_name='deliveryunit',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recycling',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_for_recycling', to='warenwirtschaft.material'),
        ),
        migrations.AlterField(
            model_name='recycling',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Abholung'), (4, 'Entsorgung')]),
        ),
        migrations.AlterField(
            model_name='recycling',
            name='unload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycling_for_unload', to='warenwirtschaft.unload'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='avv_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='unload',
            name='delivery_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unload_for_delivery_unit', to='warenwirtschaft.deliveryunit'),
        ),
        migrations.AlterField(
            model_name='unload',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_for_delivery_unit', to='warenwirtschaft.material'),
        ),
        migrations.AlterField(
            model_name='unload',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Recycling'), (3, 'Abholung'), (4, 'Entsorgung')]),
        ),
        migrations.AlterField(
            model_name='unload',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='warenwirtsc_name_d0edc8_idx'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_for_customer', to='warenwirtschaft.customer'),
        ),
        migrations.AddField(
            model_name='shippingunit',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_for_shipping_units', to='warenwirtschaft.material'),
        ),
        migrations.AddField(
            model_name='shippingunit',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units_for_shipping', to='warenwirtschaft.shipping'),
        ),
    ]
