# Generated by Django 5.1.4 on 2025-09-17 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0002_rename_delivery_receipt_barcodegenerator_receipt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcodegenerator',
            name='barcode_image',
        ),
        migrations.RemoveField(
            model_name='deliveryunit',
            name='barcode_image',
        ),
        migrations.RemoveField(
            model_name='unload',
            name='barcode_image',
        ),
    ]
