# Generated by Django 5.1.4 on 2025-01-09 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0002_alter_deliveryunits_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unloading',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_supplier', to='warenwirtschaft.supplier'),
        ),
    ]
