# Generated by Django 5.1.4 on 2025-05-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0003_customer_shipping_shippingunit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryunit',
            name='material_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recycling',
            name='material_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shippingunit',
            name='material_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unload',
            name='material_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
