# Generated by Django 5.1.4 on 2025-06-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0003_reusablebarcode_area_alter_reusablebarcode_box_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reusablebarcode',
            name='delivery_receipt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reusablebarcode',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reusablebarcode',
            name='area',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Eingang'), (2, 'Umladung'), (3, 'Aufbereitung'), (4, 'Abholung'), (5, 'Entsorgung'), (6, 'Zusatzdaten')], null=True),
        ),
        migrations.AlterField(
            model_name='reusablebarcode',
            name='target',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Eingang'), (2, 'Umladung'), (3, 'Aufbereitung'), (4, 'Abholung'), (5, 'Entsorgung')], null=True),
        ),
    ]
