# Generated by Django 5.1.4 on 2025-09-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0003_remove_barcodegenerator_barcode_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryunit',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Eingang'), (1, 'Aktiv'), (4, 'Erledigt')], default=0),
        ),
    ]
