# Generated by Django 5.1.4 on 2025-07-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0004_reusablebarcode_delivery_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='material_delivery'),
        ),
        migrations.AddField(
            model_name='material',
            name='recycling',
            field=models.BooleanField(default=False, verbose_name='material_recycling'),
        ),
        migrations.AddField(
            model_name='material',
            name='unload',
            field=models.BooleanField(default=False, verbose_name='material_unload'),
        ),
    ]
