# Generated by Django 5.1.4 on 2025-06-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0004_deliveryunit_material_other_recycling_material_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingunit',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Aktiv'), (2, 'Erledigt')], default=1),
        ),
        migrations.AlterField(
            model_name='deliveryunit',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Umladung'), (2, 'Recycling'), (3, 'Abholung'), (4, 'Entsorgung')]),
        ),
    ]
