# Generated by Django 5.1.4 on 2025-10-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0004_alter_deliveryunit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryunit',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Aktiv'), (4, 'Erledigt')], default=1),
        ),
        migrations.AlterField(
            model_name='unload',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Aktiv'), (2, 'Bereit für Behandlung'), (3, 'Bereit für Abholung'), (4, 'Erledigt')], default=1),
        ),
    ]
