# Generated by Django 5.1.4 on 2025-11-04 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0005_alter_deliveryunit_status_alter_unload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='recycling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recycling_for_shipping', to='warenwirtschaft.recycling'),
        ),
    ]
