# Generated by Django 5.1.4 on 2025-07-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0005_material_delivery_material_recycling_material_unload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recycling',
            name='unload',
        ),
        migrations.AddField(
            model_name='recycling',
            name='unloads',
            field=models.ManyToManyField(related_name='recycling_for_unload', to='warenwirtschaft.unload'),
        ),
    ]
