# Generated by Django 5.1.4 on 2025-06-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0005_shippingunit_status_alter_deliveryunit_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
