# Generated by Django 5.1.4 on 2025-06-05 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0006_delivery_barcode_delivery_barcode_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReusableBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('box_type', models.PositiveSmallIntegerField(choices=[(1, 'Gitterbox'), (2, 'Palette'), (3, 'Container'), (4, 'Ohne Behälter')])),
                ('target', models.PositiveSmallIntegerField(choices=[(1, 'Umladung'), (2, 'Recycling'), (3, 'Abholung'), (4, 'Entsorgung')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_for_barcode', to='warenwirtschaft.material')),
            ],
        ),
    ]
