# Generated by Django 5.1.4 on 2025-07-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0006_remove_recycling_unload_recycling_unloads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryunit',
            name='target',
        ),
        migrations.AlterField(
            model_name='recycling',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Aktiv'), (2, 'Lieferbar')], default=1),
        ),
        migrations.AlterField(
            model_name='reusablebarcode',
            name='area',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Eingang'), (2, 'Vorsortierung'), (3, 'Aufbereitung'), (4, 'Abholung')], null=True),
        ),
        migrations.AlterField(
            model_name='reusablebarcode',
            name='target',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Aufbereitung'), (2, 'Abholung'), (3, 'Entsorgung')], null=True),
        ),
    ]
