# Generated by Django 5.1.4 on 2025-11-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0006_shipping_recycling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='recycling',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='unload',
        ),
    ]
