# Generated by Django 5.1.4 on 2025-06-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0007_reusablebarcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='reusablebarcode',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
