# Generated by Django 5.1.4 on 2025-11-22 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0007_remove_shipping_recycling_remove_shipping_unload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recycling',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Aktiv'), (3, 'Bereit für Abholung'), (4, 'Erledigt'), (5, 'Bereit für Halle 2')], default=1),
        ),
        migrations.AlterField(
            model_name='unload',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Aktiv'), (2, 'Bereit für Behandlung'), (3, 'Bereit für Abholung'), (4, 'Erledigt'), (5, 'Bereit für Halle 2')], default=1),
        ),
        migrations.CreateModel(
            name='DeviceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.PositiveSmallIntegerField(choices=[(1, 'Unload'), (2, 'Recycling')])),
                ('box_type', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warenwirtschaft.material')),
                ('recycling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electro_tests', to='warenwirtschaft.recycling')),
                ('unload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electro_tests', to='warenwirtschaft.unload')),
            ],
        ),
    ]
