# Generated by Django 5.1.4 on 2025-08-12 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0007_remove_deliveryunit_target_alter_recycling_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='recycling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recycling_for_shipping', to='warenwirtschaft.recycling'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='unload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unload_for_shipping', to='warenwirtschaft.unload'),
        ),
        migrations.AlterField(
            model_name='reusablebarcode',
            name='area',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Eingang'), (2, 'Vorsortierung'), (3, 'Abholung')], null=True),
        ),
    ]
