# Generated by Django 5.1.4 on 2025-08-12 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0008_shipping_recycling_shipping_unload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='recycling',
        ),
        migrations.AddField(
            model_name='recycling',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recycling_for_shipping', to='warenwirtschaft.shipping'),
        ),
        migrations.AddField(
            model_name='unload',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unload_for_shipping', to='warenwirtschaft.shipping'),
        ),
    ]
