# Generated by Django 5.1.4 on 2025-12-07 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0008_alter_recycling_status_alter_unload_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.PositiveSmallIntegerField(choices=[(2, 'Vorsortierung: Laufend'), (3, 'Vorsortierung: Abholbereit'), (4, 'Aufbereitung: Abholbereit'), (5, 'Aufbereitung: Laufend'), (6, 'Aufbereitung: Abholbereit'), (7, 'Halle 2: Abholbereit'), (8, 'Halle 2: Laufend'), (9, 'Halle 2: Abholbereit')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnloadWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.PositiveSmallIntegerField(choices=[(2, 'Vorsortierung: Laufend'), (3, 'Vorsortierung: Abholbereit'), (4, 'Aufbereitung: Abholbereit'), (5, 'Aufbereitung: Laufend'), (6, 'Aufbereitung: Abholbereit'), (7, 'Halle 2: Abholbereit'), (8, 'Halle 2: Laufend'), (9, 'Halle 2: Abholbereit')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='warenwirtsc_name_d0edc8_idx',
        ),
        migrations.RemoveField(
            model_name='barcodegenerator',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='barcodegenerator',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='deliveryunit',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='deliveryunit',
            name='material_other',
        ),
        migrations.RemoveField(
            model_name='deliveryunit',
            name='status',
        ),
        migrations.RemoveField(
            model_name='deliveryunit',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='devicecheck',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='devicecheck',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='devicecheck',
            name='status',
        ),
        migrations.RemoveField(
            model_name='devicecheck',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='material',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='material',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='recycling',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='recycling',
            name='material_other',
        ),
        migrations.RemoveField(
            model_name='recycling',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='unload',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='unload',
            name='material_other',
        ),
        migrations.RemoveField(
            model_name='unload',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='deliveryunit',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryunit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='devicecheck',
            name='purpose',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Interne Verwendung'), (2, 'Online-Verkauf'), (3, 'Barverkauf'), (4, 'Geschenk'), (5, 'Austausch')], null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='device_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recycling',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recycling',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unload',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unload',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='barcodegenerator',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='barcodegenerator',
            name='box_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Container'), (2, 'Gitterbox'), (3, 'Palette'), (4, 'Wagen'), (5, 'Ohne Behälter')], null=True),
        ),
        migrations.AlterField(
            model_name='barcodegenerator',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcodes', to='warenwirtschaft.customer'),
        ),
        migrations.AlterField(
            model_name='barcodegenerator',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcodes', to='warenwirtschaft.material'),
        ),
        migrations.AlterField(
            model_name='barcodegenerator',
            name='transport',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Kunde'), (2, 'Eigen')], null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='warenwirtschaft.customer'),
        ),
        migrations.AlterField(
            model_name='deliveryunit',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='deliveryunit',
            name='box_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Container'), (2, 'Gitterbox'), (3, 'Palette'), (4, 'Wagen'), (5, 'Ohne Behälter')], null=True),
        ),
        migrations.AlterField(
            model_name='deliveryunit',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_units', to='warenwirtschaft.delivery'),
        ),
        migrations.AlterField(
            model_name='deliveryunit',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_units', to='warenwirtschaft.material'),
        ),
        migrations.AlterField(
            model_name='devicecheck',
            name='box_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Container'), (2, 'Gitterbox'), (3, 'Palette'), (4, 'Wagen'), (5, 'Ohne Behälter')], null=True),
        ),
        migrations.AlterField(
            model_name='devicecheck',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_checks', to='warenwirtschaft.material'),
        ),
        migrations.AlterField(
            model_name='devicecheck',
            name='recycling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_checks', to='warenwirtschaft.recycling'),
        ),
        migrations.AlterField(
            model_name='devicecheck',
            name='unload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_checks', to='warenwirtschaft.unload'),
        ),
        migrations.AlterField(
            model_name='material',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='recycling',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='unload',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recycling',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recycling',
            name='box_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Container'), (2, 'Gitterbox'), (3, 'Palette'), (4, 'Wagen'), (5, 'Ohne Behälter')], null=True),
        ),
        migrations.AlterField(
            model_name='recycling',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recyclings', to='warenwirtschaft.material'),
        ),
        migrations.AlterField(
            model_name='recycling',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recyclings', to='warenwirtschaft.shipping'),
        ),
        migrations.AlterField(
            model_name='recycling',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Vorsortierung: Laufend'), (3, 'Vorsortierung: Abholbereit'), (4, 'Aufbereitung: Abholbereit'), (5, 'Aufbereitung: Laufend'), (6, 'Aufbereitung: Abholbereit'), (7, 'Halle 2: Abholbereit'), (8, 'Halle 2: Laufend'), (9, 'Halle 2: Abholbereit')], default=5),
        ),
        migrations.AlterField(
            model_name='recycling',
            name='unloads',
            field=models.ManyToManyField(related_name='recyclings', to='warenwirtschaft.unload'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippings', to='warenwirtschaft.customer'),
        ),
        migrations.AlterField(
            model_name='unload',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='unload',
            name='box_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Container'), (2, 'Gitterbox'), (3, 'Palette'), (4, 'Wagen'), (5, 'Ohne Behälter')], null=True),
        ),
        migrations.AlterField(
            model_name='unload',
            name='delivery_units',
            field=models.ManyToManyField(related_name='unloads', to='warenwirtschaft.deliveryunit'),
        ),
        migrations.AlterField(
            model_name='unload',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unloads', to='warenwirtschaft.material'),
        ),
        migrations.AlterField(
            model_name='unload',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unloads', to='warenwirtschaft.shipping'),
        ),
        migrations.AlterField(
            model_name='unload',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Vorsortierung: Laufend'), (3, 'Vorsortierung: Abholbereit'), (4, 'Aufbereitung: Abholbereit'), (5, 'Aufbereitung: Laufend'), (6, 'Aufbereitung: Abholbereit'), (7, 'Halle 2: Abholbereit'), (8, 'Halle 2: Laufend'), (9, 'Halle 2: Abholbereit')], default=2),
        ),
        migrations.AddIndex(
            model_name='deliveryunit',
            index=models.Index(fields=['is_active'], name='warenwirtsc_is_acti_2a99a4_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['delivery'], name='warenwirtsc_deliver_3a1323_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['unload'], name='warenwirtsc_unload_4a149b_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['recycling'], name='warenwirtsc_recycli_40207b_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['device_check'], name='warenwirtsc_device__eb5bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='recycling',
            index=models.Index(fields=['status'], name='warenwirtsc_status_8338db_idx'),
        ),
        migrations.AddIndex(
            model_name='shipping',
            index=models.Index(fields=['is_active'], name='warenwirtsc_is_acti_667582_idx'),
        ),
        migrations.AddIndex(
            model_name='unload',
            index=models.Index(fields=['status'], name='warenwirtsc_status_18b039_idx'),
        ),
        migrations.AddField(
            model_name='recyclingweight',
            name='recycling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='warenwirtschaft.recycling'),
        ),
        migrations.AddField(
            model_name='unloadweight',
            name='unload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='warenwirtschaft.unload'),
        ),
        migrations.AddIndex(
            model_name='recyclingweight',
            index=models.Index(fields=['status'], name='warenwirtsc_status_45c42b_idx'),
        ),
        migrations.AddIndex(
            model_name='unloadweight',
            index=models.Index(fields=['status'], name='warenwirtsc_status_5eede3_idx'),
        ),
    ]
