# Generated by Django 5.1.4 on 2025-06-13 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0008_reusablebarcode_barcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reusablebarcode',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_supplier', to='warenwirtschaft.supplier'),
        ),
        migrations.AlterField(
            model_name='reusablebarcode',
            name='box_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Gitterbox'), (2, 'Palette'), (3, 'Container'), (4, 'Ohne Behälter')], null=True),
        ),
        migrations.AlterField(
            model_name='reusablebarcode',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_for_barcode', to='warenwirtschaft.material'),
        ),
        migrations.AlterField(
            model_name='reusablebarcode',
            name='target',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Umladung'), (2, 'Recycling'), (3, 'Abholung'), (4, 'Entsorgung')], null=True),
        ),
    ]
