# Generated by Django 5.1.4 on 2025-06-15 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0009_reusablebarcode_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reusablebarcode',
            name='step',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Lieferung'), (2, 'Umladung'), (3, 'Recycling'), (4, 'Versand')], null=True),
        ),
        migrations.AlterField(
            model_name='reusablebarcode',
            name='box_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Gitterbox'), (2, 'Palette'), (3, 'Gelbe Waagen'), (4, 'Ohne Behälter')], null=True),
        ),
        migrations.AlterField(
            model_name='reusablebarcode',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_for_barcode', to='warenwirtschaft.supplier'),
        ),
    ]
