# Generated by Django 5.1.4 on 2025-08-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0009_remove_shipping_recycling_recycling_shipping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recycling',
            name='target',
        ),
        migrations.RemoveField(
            model_name='reusablebarcode',
            name='target',
        ),
        migrations.RemoveField(
            model_name='unload',
            name='target',
        ),
        migrations.AlterField(
            model_name='recycling',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Aktiv'), (3, 'Abholung'), (4, 'Erledigt')], default=1),
        ),
        migrations.AlterField(
            model_name='unload',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Aktiv'), (2, 'Behandlung'), (3, 'Abholung'), (4, 'Erledigt')], default=1),
        ),
    ]
