# Generated by Django 5.1.4 on 2026-02-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0010_deliveryunit_status_alter_recycling_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryunit',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Wartet auf Vorsortierung'), (2, 'Wartet auf Zerlegung'), (3, 'Wartet auf Halle 2'), (4, 'In Vorsortierung'), (5, 'In Zerlegung'), (6, 'In Halle 2'), (7, 'Abholbereit')], default=1),
        ),
        migrations.AlterField(
            model_name='recycling',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Wartet auf Vorsortierung'), (2, 'Wartet auf Zerlegung'), (3, 'Wartet auf Halle 2'), (4, 'In Vorsortierung'), (5, 'In Zerlegung'), (6, 'In Halle 2'), (7, 'Abholbereit')], default=5),
        ),
        migrations.AlterField(
            model_name='recyclingweight',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Wartet auf Vorsortierung'), (2, 'Wartet auf Zerlegung'), (3, 'Wartet auf Halle 2'), (4, 'In Vorsortierung'), (5, 'In Zerlegung'), (6, 'In Halle 2'), (7, 'Abholbereit')]),
        ),
        migrations.AlterField(
            model_name='unload',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Wartet auf Vorsortierung'), (2, 'Wartet auf Zerlegung'), (3, 'Wartet auf Halle 2'), (4, 'In Vorsortierung'), (5, 'In Zerlegung'), (6, 'In Halle 2'), (7, 'Abholbereit')], default=4),
        ),
        migrations.AlterField(
            model_name='unloadweight',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Wartet auf Vorsortierung'), (2, 'Wartet auf Zerlegung'), (3, 'Wartet auf Halle 2'), (4, 'In Vorsortierung'), (5, 'In Zerlegung'), (6, 'In Halle 2'), (7, 'Abholbereit')]),
        ),
    ]
