# Generated by Django 5.1.4 on 2025-06-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0010_reusablebarcode_step_alter_reusablebarcode_box_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='barcode_image',
        ),
        migrations.AddField(
            model_name='deliveryunit',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='deliveryunit',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/delivery/'),
        ),
    ]
