# Generated by Django 5.1.4 on 2025-08-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0010_remove_recycling_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryunit',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Aktiv'), (4, 'Erledigt')], default=1),
        ),
        migrations.AlterField(
            model_name='recycling',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Aktiv'), (3, 'Bereit für Abholung'), (4, 'Erledigt')], default=1),
        ),
        migrations.AlterField(
            model_name='unload',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Aktiv'), (2, 'Bereit für Zerlegung'), (3, 'Bereit für Abholung'), (4, 'Erledigt')], default=1),
        ),
    ]
