# Generated by Django 5.1.4 on 2025-08-19 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0011_alter_deliveryunit_status_alter_recycling_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unload',
            name='delivery_unit',
        ),
        migrations.AlterField(
            model_name='unload',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_for_unload', to='warenwirtschaft.material'),
        ),
        migrations.AddField(
            model_name='unload',
            name='delivery_unit',
            field=models.ManyToManyField(related_name='unload_for_delivery_unit', to='warenwirtschaft.deliveryunit'),
        ),
    ]
