# Generated by Django 5.1.4 on 2025-06-21 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0011_remove_delivery_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='recycling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_for_recycling', to='warenwirtschaft.recycling'),
        ),
        migrations.AlterField(
            model_name='reusablebarcode',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/reusable'),
        ),
    ]
