# Generated by Django 5.1.4 on 2026-02-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0011_alter_deliveryunit_status_alter_recycling_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicecheck',
            name='material',
        ),
        migrations.RemoveField(
            model_name='devicecheck',
            name='recycling',
        ),
        migrations.RemoveField(
            model_name='devicecheck',
            name='unload',
        ),
        migrations.RemoveField(
            model_name='recyclingweight',
            name='recycling',
        ),
        migrations.RemoveField(
            model_name='unloadweight',
            name='unload',
        ),
        migrations.RemoveIndex(
            model_name='deliveryunit',
            name='warenwirtsc_is_acti_2a99a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='shipping',
            name='warenwirtsc_is_acti_667582_idx',
        ),
        migrations.RemoveField(
            model_name='deliveryunit',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='recycling',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='inactive_at',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='unload',
            name='is_active',
        ),
        migrations.AddField(
            model_name='unload',
            name='device_check',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unload',
            name='device_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryunit',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Wartet auf Vorsortierung'), (3, 'Wartet auf Zerlegung'), (5, 'Wartet auf Halle 2'), (7, 'Abholbereit'), (2, 'In Vorsortierung'), (4, 'In Zerlegung'), (6, 'In Halle 2'), (8, 'Erledigt')], default=1),
        ),
        migrations.AlterField(
            model_name='recycling',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Wartet auf Vorsortierung'), (3, 'Wartet auf Zerlegung'), (5, 'Wartet auf Halle 2'), (7, 'Abholbereit'), (2, 'In Vorsortierung'), (4, 'In Zerlegung'), (6, 'In Halle 2'), (8, 'Erledigt')], default=4),
        ),
        migrations.AlterField(
            model_name='unload',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Wartet auf Vorsortierung'), (3, 'Wartet auf Zerlegung'), (5, 'Wartet auf Halle 2'), (7, 'Abholbereit'), (2, 'In Vorsortierung'), (4, 'In Zerlegung'), (6, 'In Halle 2'), (8, 'Erledigt')], default=2),
        ),
        migrations.DeleteModel(
            name='DeviceCheck',
        ),
        migrations.DeleteModel(
            name='RecyclingWeight',
        ),
        migrations.DeleteModel(
            name='UnloadWeight',
        ),
    ]
