# Generated by Django 5.1.4 on 2025-08-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0012_remove_unload_delivery_unit_alter_unload_material_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unload',
            old_name='delivery_unit',
            new_name='delivery_units',
        ),
    ]
