# Generated by Django 5.1.4 on 2026-03-02 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0012_remove_devicecheck_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HalleZwei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Wartet auf Vorsortierung'), (3, 'Wartet auf Zerlegung'), (5, 'Wartet auf Halle 2'), (7, 'Abholbereit'), (2, 'In Vorsortierung'), (4, 'In Zerlegung'), (6, 'In Halle 2'), (8, 'Erledigt')], default=6)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('halle_zwei', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inactive_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='material',
            name='warenwirtsc_device__eb5bdc_idx',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='device_check',
            new_name='halle_zwei',
        ),
        migrations.RemoveField(
            model_name='unload',
            name='device_check',
        ),
        migrations.RemoveField(
            model_name='unload',
            name='device_check_at',
        ),
        migrations.AddField(
            model_name='delivery',
            name='b2b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryunit',
            name='halle_zwei',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryunit',
            name='halle_zwei_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryunit',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halle_zwei', to='warenwirtschaft.shipping'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['halle_zwei'], name='warenwirtsc_halle_z_9dbdd0_idx'),
        ),
        migrations.AddField(
            model_name='hallezwei',
            name='delivery_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_to_halle_zwei', to='warenwirtschaft.deliveryunit'),
        ),
        migrations.AddField(
            model_name='hallezwei',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_to_halle_zwei', to='warenwirtschaft.shipping'),
        ),
    ]
