# Generated by Django 5.1.4 on 2025-06-21 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0012_shipping_recycling_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='recycling',
        ),
        migrations.AddField(
            model_name='shippingunit',
            name='recycling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_units_for_recycling', to='warenwirtschaft.recycling'),
        ),
        migrations.AlterField(
            model_name='shippingunit',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_units_for_shipping', to='warenwirtschaft.shipping'),
        ),
    ]
