# Generated by Django 5.1.4 on 2026-03-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0013_hallezwei_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryunit',
            name='halle_zwei',
        ),
        migrations.RemoveField(
            model_name='deliveryunit',
            name='halle_zwei_at',
        ),
    ]
