# Generated by Django 5.1.4 on 2025-06-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0013_remove_shipping_recycling_shippingunit_recycling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='transport',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Kunde'), (2, 'Eigen')]),
        ),
    ]
