# Generated by Django 5.1.4 on 2026-03-14 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0014_remove_deliveryunit_halle_zwei_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallezwei',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='halle_zweis', to='warenwirtschaft.shipping'),
        ),
    ]
