# Generated by Django 5.1.4 on 2025-06-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warenwirtschaft', '0014_alter_shipping_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='unload',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='unload',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/unload/'),
        ),
    ]
