from .delivery_list_view import DeliveryListView
from .delivery_create_view import DeliveryCreateView
from .delivery_update_view import DeliveryUpdateView
from .delivery_detail_weight_view import DeliveryDetailWeightView
from .delivery_detail_barcode_view import DeliveryDetailBarcodeView
from .delivery_delete_view import DeliveryDeleteView
